version: '3.8'
services:
  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    environment:
      - TZ=Asia/Tokyo
    working_dir: /var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: campsite
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

